# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestInvalidEmailFormatValidation():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_invalidEmailFormatValidation(self):
    self.driver.get("https://demoqa.com/automation-practice-form")
    self.driver.set_window_size(1366, 768)
    self.driver.execute_script("window.scrollTo(0,488)")
    self.driver.find_element(By.ID, "firstName").click()
    self.driver.find_element(By.ID, "firstName").send_keys("Dilshani")
    self.driver.find_element(By.ID, "lastName").click()
    self.driver.find_element(By.ID, "lastName").send_keys("Chamodika")
    self.driver.find_element(By.CSS_SELECTOR, ".custom-radio:nth-child(2) > .custom-control-label").click()
    self.driver.find_element(By.ID, "userNumber").click()
    self.driver.find_element(By.ID, "userNumber").send_keys("0715289816")
    self.driver.find_element(By.ID, "userEmail").click()
    self.driver.find_element(By.ID, "userEmail").send_keys("k.d.chamodikagmail.com")
    self.driver.execute_script("window.scrollTo(0,891)")
    self.driver.find_element(By.ID, "submit").click()

    time.sleep(1)
    self.driver.execute_script("window.scrollTo(0,488)")
    border_color = self.driver.find_element(By.ID, "userNumber").value_of_css_property("border-color")
    assert border_color == "rgb(40, 167, 69)", f"Expected red border color, but got '{border_color}'"
  
